import React from 'react'
import './style/index.css'
class ClockBg extends React.Component{
  constructor(){
    super()
  }
  render(){
    return (
      <div className="bg">
        <div className='intro'>
        <div className='center'>
          <div className='core'></div>
          <div className='outer_one'>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
            <div className='outer_one__piece'></div>
          </div>
          <div className='outer_two'>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
            <div className='outer_two__piece'></div>
          </div>
          <div className='outer_three'>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
            <div className='outer_three__piece'></div>
          </div>
          <div className='outer_four'>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
            <div className='outer_four__piece'></div>
          </div>
          <div className='outer_five'>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
            <div className='outer_five__piece'></div>
          </div>

          <div className='pieces'>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
            <div className='future_ui__piece blank'></div>
          </div>
        </div>
      </div>
      </div>
    )
  }
}

export default ClockBg
